catalog:
  featured_movies:
    - 299536  # Avengers: Endgame
    - 550  # Fight Club
    - 278  # The Shawshank Redemption
    - 496243  # Top Gun: Maverick
    - 680  # Pulp Fiction
    - 109  # Sunrise
    - 129  # Singin' in the Rain
    - 238  # The Godfather
    - 240  # The Godfather Part II
    - 424  # Schindler's List
    - 389  # Tremors
    - 505642  # Black Widow
    - 338762  # Three Thousand Years of Longing
    - 346698  # Avatar: The Way of Water
    - 16662  # Blade Runner
    - 11  # Star Wars
    - 13  # Forrest Gump
    - 278935  # Deadpool & Wolverine
    - 299534  # Avengers: Infinity War
    - 808  # Platoon
