doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_sqlite'
        server_version: '3'
        charset: utf8mb4

    orm:
        auto_generate_proxy_classes: true
        proxy_namespace: App\Doctrine\Proxies
        proxy_dir: '%kernel.project_dir%/var/cache/doctrine/proxies'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Entity'
                prefix: 'App\Shared\Infrastructure\Persistence\Entity'
                alias: App
