easy_admin:
    site_name: 'Movie Rental Admin'

    dashboards:
        admin:
            class: App\Controller\Admin\DashboardController
            title: 'Admin Dashboard'

    entities:
        User:
            class: App\Entity\User
            label: 'Users'

        Transaction:
            class: App\Entity\Transaction
            label: 'Transactions'
