framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    php_errors:
        log: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    webhook:
        routing:
            stripe:
                service: integration_engine.webhook_parser.stripe
                secret: ~ # ignored; IntegrationEngine uses its own secret from YAML config
