integration_engine:
    integrations:
        tmdb:
            base_url: '%env(string:TMDB_BASE_URL)%'
            headers:
                Authorization: 'Bearer %env(string:TMDB_ACCESS_TOKEN)%'
            middlewares:
                - app.middleware.rate_limit
        countries:
            base_url: 'https://countries.trevorblades.com'
            client_service: integration_engine.client.graphql
