framework:
    rate_limiter:
        # tour:start config/rate-limiter
        api_requests:
            policy: 'fixed_window'
            limit: 1000
            interval: '1 hour'
        # tour:end config/rate-limiter
