services:
  App\Tour\Infrastructure\YamlTourRegistry:
    arguments:
      $configPath: '%kernel.project_dir%/config/tour.yaml'
    public: true

  App\Tour\Domain\TourRegistry: '@App\Tour\Infrastructure\YamlTourRegistry'
