services:
  php:
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    ports:
      - "80:80"
      - "443:443"

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
###< symfony/mercure-bundle ###
